### PR TITLE
Promote challenge fee management to prod

### PR DESCRIPTION
**Pull request by ajefts**

### CODE REVIEW

**Comment by cwdcwd** [comment]
@skyhit is all this new code covered with unit tests?

**Comment by cwdcwd** [comment]
@skyhit ☝️

**Comment by skyhit** [comment]
@cwdcwd no, but  did with functional test

**Comment by cwdcwd** [comment]
there's a lot of old commits in here and I want to ensure that everything is going to work. 
I'll accept this merge but can you run a challenge/task to get unit test coverage up to date on everything here?

**Comment by skyhit** [comment]
@cwdcwd ok

**Pull request merged**
