### PR TITLE
Challenge fee api for admin app

### PR DESCRIPTION
**Pull request by huangqun**
@ajefts please check this.

### CODE REVIEW

**Comment by skyhit** [comment]
@huangqun @ajefts what is the different from this - https://github.com/topcoder-platform/tc-billing-account-service/pull/31

**Comment by huangqun** [comment]
@skyhit I honestly don't know, did you also create new endpoints to manage challenge fees?

**Comment by skyhit** [comment]
@huangqun yes, Tony asked to, so seems we are doing the same work:)

**Comment by huangqun** [comment]
@skyhit do you mind checking if they are actually the same? If so you can discard mine and keep yours.

**Pull request closed without merging**
